[project]
name = "beyond-chatgpt"
version = "0.1.0"
description = "gpt-like-a-dev"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "jupyter",
    "openai",
    "pydantic",
    "python-dotenv",
    "python-multipart",
    "uvicorn",
]
